// const USER_LOGIN = 'USER_LOGIN'
// const USER_LOGOUT = 'USER_LOGOUT'
// const USER_REGISTER = 'USER_REGISTER'
// const USER_CHANGE_PASS = 'USER_CHANGE_PASS' 


const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE'

export {USER_REGISTER_REQUEST, USER_REGISTER_SUCCESS, USER_REGISTER_FAILURE}