// const USER_LOGIN = 'USER_LOGIN'
// const USER_LOGOUT = 'USER_LOGOUT'
// const USER_REGISTER = 'USER_REGISTER'
// const USER_CHANGE_PASS = 'USER_CHANGE_PASS' 


const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE'

const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'

const USER_LOGOUT = 'USER_LOGOUT'
const UPDATE_USER_INFO = 'UPDATE_USER_INFO'

export {USER_REGISTER_REQUEST, USER_REGISTER_SUCCESS, USER_REGISTER_FAILURE,
        USER_LOGIN_REQUEST, USER_LOGIN_SUCCESS, USER_LOGIN_FAILURE,
        USER_LOGOUT, UPDATE_USER_INFO
}
        // USER_LOGOUT_REQUEST, USER_LOGOUT_SUCCESS, USER_LOGOUT_FAILURE