# Generated by Django 3.0.5 on 2020-04-09 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
