# Generated by Django 3.0.5 on 2020-05-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20200504_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tagline',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
