# Generated by Django 3.0.5 on 2020-05-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_post_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='background',
            field=models.ImageField(default='blog_background/default.png', upload_to='blog_background/'),
        ),
    ]
