# Generated by Django 3.0.5 on 2020-05-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_post_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='background',
            field=models.ImageField(default='blog_background/default.jpg', upload_to='blog_background/'),
        ),
    ]
