# Generated by Django 3.0.5 on 2020-05-31 10:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('company', models.CharField(blank=True, max_length=30, null=True)),
                ('interest', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(default='profile_pictures/default.png', upload_to='profile_pictures/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('USN', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, default='')),
                ('linkedIn_ID', models.URLField(blank=True, default='')),
                ('github_ID', models.URLField(blank=True, default='')),
                ('codechef_id', models.CharField(blank=True, max_length=30, null=True)),
                ('codeforces_id', models.CharField(blank=True, max_length=30, null=True)),
                ('hackerrank_id', models.CharField(blank=True, max_length=30, null=True)),
                ('sem', models.CharField(blank=True, max_length=100, null=True)),
                ('skills', models.ManyToManyField(blank=True, to='auths.Skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('domains', models.CharField(blank=True, max_length=100, null=True)),
                ('duration_from', models.DateField(default=datetime.date.today, verbose_name='Date From')),
                ('duration_to', models.DateField(blank=True, null=True, verbose_name='Date To')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auths.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=200)),
                ('course', models.CharField(blank=True, max_length=10, null=True)),
                ('duration_from', models.DateField(default=datetime.date.today, verbose_name='Date From')),
                ('duration_to', models.DateField(blank=True, null=True, verbose_name='Date To')),
                ('score', models.CharField(blank=True, max_length=10, null=True)),
                ('descriptions', models.TextField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auths.UserProfile')),
            ],
        ),
    ]
