# Generated by Django 3.0.5 on 2020-05-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_auto_20200505_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='codechef_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='codeforces_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hackerrank_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
